name: 'Trigger UCD API'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # UCD Application
    description: 'Name of the UCD application'
    required: true
    default: 'MYAPP'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'