name: 'Deploy UCD aapplication'
description: 'Run UCD Application Process Request '
inputs:
  application:
    description: 'Application Name'
    required: true
  applicationProcess:
    description: 'Application Process Name'
    required: true
  environment:
    description: 'Environment Name'
    required: true
  onlyChanged:
    description: 'onlyChanged'
    required: false
    type: boolean
    default: false
  versions:
    description: '1 ore more Versions'
    required: true
    type: String
  hostname:
    description: 'UCD hostname'
    required: true
  port:
    description: 'port'
    required: true
    default: '8443'
  username:
    description: 'username'
    required: true
  password:
    description: 'password'
    required: true
    secret: true
  disableSSLVerification:
    description: 'skip SSL certificate validation when making HTTPS requests and this is discouraged'
    required: true
    type: boolean
    default: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'