on: [push]

jobs:
  hello_world_job:
    runs-on: javascript-action-runner
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: kblogin123456/hello-world-javascript-action@v1.12
        with:
          application: 'MYAPP'
          applicationProcess: 'DEPLOY-HFS'
          environment: 'DEV'
          versions: 'hfs_only_rabo_uid'
          component: 'MYCOMP'
          hostname: '10.134.119.177'
          username: 'admin'
          password: '${{ secrets.UCD_PASSWORD }}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
