on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - 'main'
jobs:
  hello_world_job:
    runs-on: self-hosted
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: Amiya-873/hello-world-javascript-action@main
        with:
          application: 'helloApplication'
          applicationProcess: 'app-process'
          environment: 'Ene-Jen'
          properties: ''
          snapshot: ''
          versions: '[{"version": "1","component": "helloWorld"}]'
          hostname: 'localhost'
          username: 'admin'
          password: 'adm'
          authtoken: ''

