on:
  workflow_dispatch:
    inputs:
      version-input:
        description: 'Versions to deploy'

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: kblogin123456/hello-world-javascript-action@v1.19
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          propeties: '{"prop1":"Hello IBM", "prop2":"Hello UCD"}'
          versions: '[{"version": "TEMP1-JCLA", "component": "MYCOMP"},{"version": "File1","component": "Regular component"}]'
          hostname: '10.134.119.177'
          username: 'admin'
          password: '${{ secrets.UCD_PASSWORD }}'

